---
# Starter pipeline

parameters:
   - name: 'destenv'
     displayName: 'Environmet to copy thumbnails (qa,stg)'
     type: string

variables:
  - name: storageAccount-qa
    value: 'hardacinfrthmb00saqa'
  
  - name: storageAccount-stg
    value: 'hardacinfrthmb00sastg'
  
  - name: storageAccount-prd
    value: 'hardacinfrthmb00saprd'
  
  - name: serviceConnection-qa
    value: 'HARDAC-Qa'
  
  - name: serviceConnection-stg
    value: 'HARDAC-Stage'
  
  - name: serviceConnection-prd
    value: 'HARDAC-Prod'

  
  - name: serviceConnection-gon
    value: 'HARDAC-Backup'
  - name: storageAccount-gon
    value: 'gonzalocopy1'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'Trigger_Copy_thumbnails'
    displayName: 'Copy Thumbnails from production to ${{ parameters.destenv }}'
    condition: succeeded()
    jobs:
      - job: "Build_Pipeline"
        variables:
          job_variable: $(storageAccount-${{ parameters.destenv }})
        displayName: 'Copy Thumbnails from production to ${{ parameters.destenv }}'
        timeoutInMinutes: 10
        steps:
          - task: AzureCLI@1
            name: GenerateSASSource
            displayName: 'Generate SAS token for Thumbnails for production storage account'
            env:
              AZURE_STORAGE_AUTH_MODE: login
            inputs:
              azureSubscription: 'HARDAC-Backup'
              #$(serviceConnection-prd)
              scriptLocation: inlineScript
              workingDirectory: $(Build.SourcesDirectory)/mlops
              inlineScript: |
                echo 'Generate SAS Token for source'
                end=`date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ'`
                sasSource=$(az storage account generate-sas --permissions acdlpruw --account-name $(storageAccount-prd) --services bfqt --resource-types sco --expiry $end -o tsv)
                echo "##vso[task.setvariable variable=sasSource]$sasSource"
                echo $sasSource           
              artifact: variables
          
          - task: AzureCLI@1
            name: GenerateSASDestination
            displayName: 'Generate SAS token for Thumbnails for ${{ parameters.destenv }} storage account'
            env:
              AZURE_STORAGE_AUTH_MODE: login
            inputs:
              azureSubscription: $(serviceConnection-${{ parameters.destenv }})
              scriptLocation: inlineScript
              workingDirectory: $(Build.SourcesDirectory)/mlops
              inlineScript: |
                
                end=`date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ'`
                
                echo 'Generate SAS Token for Destination'
                sasDestination=$(az storage account generate-sas --permissions acdlpruw --account-name $(storageAccount-${{ parameters.destenv }}) --services bfqt --resource-types sco --expiry $end -o tsv)
                echo "##vso[task.setvariable variable=sasDestination]$sasDestination"
                echo $sasDestination              
              artifact: variables
            
          - task: AzureCLI@1
            name: Copy
            env:
              AZURE_STORAGE_AUTH_MODE: login
            inputs:
              azureSubscription: $(serviceConnection-${{ parameters.destenv }})
              scriptLocation: inlineScript
              workingDirectory: $(Build.SourcesDirectory)/mlops
              inlineScript: |
                
                echo "starting azcopy command"
                echo "from"
                echo "https://$(storageAccount-${{ parameters.destenv }}).blob.core.windows.net"
                echo "to"
                echo "https://$(storageAccount-prd).blob.core.windows.net"
                
                azcopy copy "https://$(storageAccount-prd).blob.core.windows.net/?$(sasSource)" "https://$(storageAccount-${{ parameters.destenv }}).blob.core.windows.net/?$(sasDestination)" --recursive --overwrite "ifSourceNewer"
              artifact: variables
