---

# Starter pipeline

variables:
  - name: SourceSA
    value: 'hardacinfrthmb00sasb'
  - name: DestinationSA
    value: 'hardacinfrthmb00saqa'

pool:
  vmImage: ubuntu-latest

stages:

  - stage: 'Trigger_Copy_thumbnails'
    displayName: 'Copy Thumbnails'
    condition: succeeded()
    jobs:
      - job: "Build_Pipeline"
        displayName: "Copy Thumbnails"
        timeoutInMinutes: 10
        steps:
          - task: AzureCLI@1
            name: GenerateSASSource
            env:
              AZURE_STORAGE_AUTH_MODE: login
            inputs:
              azureSubscription: 'HARDAC-Dev'
              scriptLocation: inlineScript
              workingDirectory: $(Build.SourcesDirectory)/mlops
              inlineScript: |
                echo 'Generate SAS Token for source'

                end=`date -u -d "30 minutes" '+%Y-%m-%dT%H:%MZ'`
                sasSource=$(az storage account generate-sas --permissions acdlpruw --account-name $(SourceSA) --services bfqt --resource-types sco --expiry $end -o tsv)
                echo "CREATED"
                echo "##vso[task.setvariable variable=sasSource]$sasSource"
                echo $sasSource
                
                sasDestination=$(az storage account generate-sas --permissions acdlpruw --account-name $(DestinationSA) --services bfqt --resource-types sco --expiry $end -o tsv)
                echo $sasDestination

                echo "starting azcopy command"
                echo "from"
                echo "https://$(SourceSA).blob.core.windows.net/?$(sasSource)"
                echo "to"
                echo "https://$(DestinationSA).blob.core.windows.net/$dateNow/?$(sasDestination)" --recursive --overwrite "ifSourceNewer"
                
                azcopy copy "https://$(SourceSA).blob.core.windows.net/?$(sasSource)" "https://$(DestinationSA).blob.core.windows.net/gonzalo/$dateNow/?$(sasDestination)" --recursive --overwrite "ifSourceNewer"
              artifact: variables
          
                
              
                
